version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/project/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/project/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "pip"
    directory: "/tools/data-generator"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5